### ISSUE TITLE
Text in panels go off page

### ISSUE THREAD

**Issue by terrellt** [osulp/building-oregon#112]
Looks like the classes need some help.

**Comment by straleyb** [comment]
Can you link an example?

**Comment by terrellt** [comment]
http://building-oregon-dev.library.oregonstate.edu/?f%5Bdesc_metadata__stylePeriod_label_sim%5D%5B%5D=Italianate+%28North+American++architecture+styles+%29%24http%3A%2F%2Fvocab.getty.edu%2Faat%2F300018207&per_page=100&q=&search_field=all_fields&view=maps Click the 10

**Comment by straleyb** [comment]
Ah cool yeah. I clicked through a ton and could only find ones with only dates haha.
