### ISSUE TITLE
Have map pull only items close to a persons location

### ISSUE THREAD

**Issue by straleyb** [osulp/building-oregon#140]
This was previously talked about when discussing the map being empty when first visiting the page. We want to try and get the map to pull data within a certain distance from that person and zoom in on that person.

What we need:

1. Spatial index fields in Oregon Digital (OregonDigital/oregondigital#834)
2. The ability for javascript to ask for points around a certain location (to populate the map after the user has given permission to view its location)
3. The ability to refresh the map with new points.

**Comment by terrellt** [comment]
I think this is closed? Some testing is probably in order.
