### ISSUE TITLE
Determine who the owner is for Building Oregon

### ISSUE THREAD

**Issue by mickeroo** [osulp/building-oregon#201]
Who is responsible for maintaining the site and handing requests for information, etc.

**Comment by jsimic** [comment]
Ed Teague: ehteague@uoregon.edu

**Comment by mellinma** [comment]
I have been getting the emails.  Does Ed wish to get them instead?  And does he want to maintain the site as well?   At least some of the errors in the site originate in Oregon Digital, not the original Content DM collection.

**Comment by mellinma** [comment]
Actually all of the metadata issues that I posted in the last week are actually Oregon Digital errors.
