### ISSUE TITLE
What should the email that is sent from contact form say?

### ISSUE THREAD

**Issue by straleyb** [osulp/building-oregon#208]
@mellinma These emails will be sent to you, so what might you want these emails to say/look like?

**Comment by mellinma** [comment]
@straleyb Can you tell me more about this?  Who sees the email?  If it's just coming to me, I need to see only that it is from Building Oregon 
But maybe you are asking what the confirmation email to the user should say?  

Thank you for your interest in Building Oregon!  Expect a reply to your email within 48 hours.  

Best regards
Margaret Mellinger 
for Building Oregon
