### ISSUE TITLE
Help page

### ISSUE THREAD

**Issue by mellinma** [osulp/building-oregon#231]
Could the help page get a little styling love?   Also, it seems redundant to have the title of the page be help and the next line "Help with Building Oregon" .  In the scheme of things this is not super important, but it might be easier to read on a small screen if there is some use of space, font hierarchies and bullets.

**Comment by mickeroo** [comment]
Some bullet points have been added, anything else @mellinma ?

**Comment by mellinma** [comment]
something happened to Use the categories.  Use displays in cyrillic or somtehing?  I'm on Chrome.
