### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by mellinma** [osulp/building-oregon#233]
Looks a bit bare and strange... styling?  The box where the message is to be is tiny.  The convention would be to make it a bit larger, so that people get the idea that they can type a paragraph, not just "hi"  
![
styling](https://cloud.githubusercontent.com/assets/11778515/8168950/42ee984a-135b-11e5-8829-4c6022caf30a.PNG)

**Comment by mickeroo** [comment]
The contact page also needs a captcha to cut down on the amount of spam email being received.

**Comment by straleyb** [comment]
1.
