### ISSUE TITLE
remove God.conf, replace with Monit.d equivalent configurations

### ISSUE THREAD

**Issue by revgum** [osulp/building-oregon#256]

**Comment by revgum** [comment]
- [ ] On production server, see the `/etc/monit.d/kiosks.l.o.e.conf` file for an example
- [ ] Copy the `shared/app.sh` and `shared/monit*.sh` that are setup in the kiosks app as an example

**Comment by straleyb** [comment]
/etc locked down to sudo. Talked to ryan about copying the file over and naming it `building-oregon.library.oregonstate.edu.conf`

**Comment by straleyb** [comment]
File added.

**Comment by straleyb** [comment]
Done long while ago
