### ISSUE TITLE
add local_env.yml

### ISSUE THREAD

**Issue by revgum** [osulp/building-oregon#258]
- [ ] Add local_eny.yml to inject environment variables to the application.
- [ ] Remove the .bashrc (or ~/app_configs/ sort of configuration) for this apps environment variables.
- [ ] Inject the ENV variables from local_env.yml in `application.rb` like so:
```
# load and inject local_env.yml key/values into ENV
    config.before_configuration do
      env_file = File.join(Rails.root, 'config', 'local_env.yml')
      if File.exist?(env_file)
        YAML.safe_load(File.open(env_file)).each do |key, value|
          ENV[key.to_s] = value
        end
      end
    end
```
- [ ] Symlink local_env.yml on server in `config/deploy.rb`

**Comment by straleyb** [comment]
done
