### ISSUE TITLE
Discuss with UO about life of application. 

### ISSUE THREAD

**Issue by straleyb** [osulp/building-oregon#280]
As per strategic planning discussions, we need to have a talk with UO about this application. If we are going to continue to host this, then we need to discuss another 2 year plan.

**Comment by straleyb** [comment]
Depending on what is decided here, if we decide to keep this app, then we will need to update blacklight, blacklight maps, and update the internal code surrounding those two pieces of the framework.

**Comment by mellinma** [comment]
The app will be sunsetted, per Ed Teague and others at UO.

**Comment by mellinma** [comment]
We do need to think about what happens to searches that formerly resolved to Building Oregon Mobile App. An example: 
When you google "Delta Zeta Sorority Eugene", the first result is from building oregon.
