### ISSUE TITLE
find image thumbnails

### ISSUE THREAD

**Issue by balesh2** [osulp/building-oregon#35]

**Comment by straleyb** [comment]
https://github.com/OregonDigital/oregondigital/blob/master/app/models/image.rb This should be a good start

**Comment by straleyb** [comment]
Wondering if we need the images in our project since it looks like they reside in Rails.root/media/"path_to_photo". @terrellt

**Comment by mickeroo** [comment]
@straleyb Here is a some examples mapping Oregon Digital objects to their medium-res images:

Item: http://oregondigital.org/sets/building-or/oregondigital:df66r985q
Image: http://oregondigital.org/media/medium-images/q/5/oregondigital-df66r985q.jpg

or 

Item: http://oregondigital.org/sets/building-or/oregondigital:df66rc64c
Image: http://oregondigital.org/media/medium-images/c/4/oregondigital-df66rc64c.jpg

Once you've got the PID (e.g. "oregondigital:df66rc64c") you can build the URL for the medium-res image it by doing some string manipulation
