### ISSUE TITLE
Move similar links in nav bar to dropdown

### ISSUE THREAD

**Issue by straleyb** [osulp/building-oregon#56]

**Comment by balesh2** [comment]
Maybe put "About Us" and "Contact Us" in one dropdown, and "Bookmarks", "Saved Searches", and "History" in another?

**Comment by straleyb** [comment]
Possibly. We were also thinking to not even provide the bookmark saved searches and history right off the bat. We could allow for that later.

**Comment by balesh2** [comment]
If we decide to not have those features available, then we shouldn't put anything in dropdowns. And without those links we wouldn't really need to.

**Comment by straleyb** [comment]
precisely! So maybe we should just delete this issue?

**Comment by straleyb** [comment]
Or change it to a question.

**Comment by balesh2** [comment]
We can leave it until we decide on the navbar issue.

**Comment by balesh2** [comment]
Fixed by #79
