### ISSUE TITLE
Create Javascript overlay

### ISSUE THREAD

**Issue by mickeroo** [osulp/building-oregon#59]
Make a transparent tutorial overlay to show people how to use the hamburger.  Hide it after the first view.

**Comment by terrellt** [comment]
Wat

**Comment by mickeroo** [comment]
This is meant to be a discussion about whether people would have trouble finding the controls if we collapse everything into a hamburger menu. A proposal was to have a "here's where things are" overlay appear the first time someone visits the site.

**Comment by terrellt** [comment]
Is a hamburger menu the three little horizontal lines that a menu gets collapsed into?

**Comment by straleyb** [comment]
@terrellt yep! you got it.
