### ISSUE TITLE
footer content

### ISSUE THREAD

**Issue by balesh2** [osulp/building-oregon#68]

**Comment by balesh2** [comment]
Do we want to add the footer to the settings that are WYSIWYG editable in the admin panel, or should it be static?

**Comment by straleyb** [comment]
I feel like having them be static is the way to go here. Since we are trying to keep this fairly similar to OD (as far as contact info, rights, copyrights, etc.) That info will all be pretty static. Does that sound accurate or did you have another idea @balesh2?

**Comment by balesh2** [comment]
Nope, that sounds good. Just thought I'd check since having be customizable is an option.

**Comment by straleyb** [comment]
:+1:

**Comment by straleyb** [comment]
@balesh2 Do you think its ok to close this issue? We are going to throw 

https://oregondigital.org/contact (contact) and
https://oregondigital.org/copyright (copyright)

into the footer and we can add more when necessary.

**Comment by straleyb** [comment]
@balesh2 ^^^^^^
