### ISSUE TITLE
show view "Tools" sidebar

### ISSUE THREAD

**Issue by balesh2** [osulp/building-oregon#72]
At the bottom of the "Tools" sidebar there is a random row that is colored yellow. We should get rid of this and probably change the heading to yellow to keep it consistent with the index view

**Comment by straleyb** [comment]
Do you think maybe we should get rid of the show tools altogether since we don't want to provide right off the bat history, bookmarking, sms messaging, emails, etc.

**Comment by balesh2** [comment]
I hadn't thought about it. But if we are getting rid of all of the features offered in "Tools", we probably should delete it
